//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneListApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int CouponID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double DiscountPercentage { get; set; }
        public int RetailID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndingDate { get; set; }
    
        public virtual Retail Retail { get; set; }
    }
}
