//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneListApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListUser
    {
        public int ListUserID { get; set; }
        public int ListID { get; set; }
        public int SuscriberGroupID { get; set; }
        public string SuscriptionDate { get; set; }
    
        public virtual List List { get; set; }
        public virtual SuscriberGroup SuscriberGroup { get; set; }
    }
}
