//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneListApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItem
    {
        public int ListID { get; set; }
        public int ItemID { get; set; }
        public bool ListItemSolved { get; set; }
        public string ListItemSolver { get; set; }
        public System.DateTime ListItemSolvingDate { get; set; }
        public Nullable<decimal> ListItemCost { get; set; }
        public string ListItemNotes { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual List List { get; set; }
        public virtual User User { get; set; }
    }
}
