//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneListApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public List()
        {
            this.ListItems = new HashSet<ListItem>();
            this.ListUsers = new HashSet<ListUser>();
        }
    
        public int ListID { get; set; }
        public string CreatorID { get; set; }
        public string ListName { get; set; }
        public int ListTypeID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int ListStatusID { get; set; }
    
        public virtual ListType ListType { get; set; }
        public virtual ListStatu ListStatu { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListItem> ListItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListUser> ListUsers { get; set; }
    }
}
